kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: efive-cluster
  namespace: fleet-default
spec:
  rkeConfig:
    machinePools:
      - controlPlaneRole: true
        etcdRole: true
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: efive-machine-selector
        name: pool1
        quantity: 1
        unhealthyNodeTimeout: 0s
        workerRole: true
  kubernetesVersion: v1.23.7+k3s1
