apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: elementt2-nodes
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
        - name: root
          passwd: root
    elemental:
      install:
        reboot: true
        device: /dev/sda
        debug: true
  machineName: elementt2-machine
  machineInventoryLabels:
    location: "elementt2europe"
