apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: ethree-nodes
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
        - name: root
          passwd: root
    elemental:
      install:
        reboot: true
        device: dev/sr0
        debug: true
  machineName: ethree-machine
  machineInventoryLabels:
    location: "ethreeeurope"
