apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: etwo-nodes
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
        - name: root
          passwd: root
    elemental:
      install:
        reboot: true
        device: /dev/sda1
        debug: true
  machineName: etwo-machine
  machineInventoryLabels:
    location: "etwoeurope"
